### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by mmatiaschek** [Welthungerhilfe/ChildGrowthMonitor#29]
- [ ] All Strings must be in strings.xml
- [ ] As a user i want to be able to choose my main language (default from system language) #26 
- [ ] the app should be able to use hindi हिन्दी letters
