### ISSUE TITLE
standardization test

### ISSUE THREAD

**Issue by mmatiaschek** [Welthungerhilfe/ChildGrowthMonitor#37]
- [ ] set up test, standardization and production environment
- [ ] remote config for standardization test
- [ ] check if multiple phones scanning one person interfere with each other (IR point clouds)

**Comment by mmatiaschek** [comment]
setting the user name for crashlytics should only be done in debug mode, for example in standardization tests:
https://github.com/Welthungerhilfe/cgm-scanner/pull/1/commits/5b8ed5331987fe7470e16714153cd679316aae6a
