### ISSUE TITLE
Stability

### ISSUE THREAD

**Issue by mmatiaschek** [Welthungerhilfe/ChildGrowthMonitor#49]
All line numbers from Tag 20180305A?

- [x] [PersonalDataFragment.java line 144](https://console.firebase.google.com/u/0/project/child-growth-monitor/crashlytics/app/android%3Ade.welthungerhilfe.cgm.scanner/issues/5a9d26d38cb3c2fa635a0f7b)
- [x] [RequestManagerRetriever.java line 134](https://console.firebase.google.com/u/0/project/child-growth-monitor/crashlytics/app/android:de.welthungerhilfe.cgm.scanner/issues/5a9d64a38cb3c2fa635e6ab1)
- [x] [BaseActivity.java line 42](https://console.firebase.google.com/u/0/project/child-growth-monitor/crashlytics/app/android:de.welthungerhilfe.cgm.scanner/issues/5aa0d4378cb3c2fa638f3e98)
- [x] [CreateDataActivity.java line 291](https://console.firebase.google.com/u/0/project/child-growth-monitor/crashlytics/app/android:de.welthungerhilfe.cgm.scanner/issues/5a9f97788cb3c2fa637c9afd)
- [ ] [RecorderActivity.java line 1020](https://console.firebase.google.com/u/0/project/child-growth-monitor/crashlytics/app/android:de.welthungerhilfe.cgm.scanner/issues/5a9e9ba68cb3c2fa636f0b63)
- [x] [BabyFront0Fragment.java line 40](https://console.firebase.google.com/u/0/project/child-growth-monitor/crashlytics/app/android:de.welthungerhilfe.cgm.scanner/issues/5aa1085f8cb3c2fa63926ab4)
- [x] [LoginActivity.java line 83](https://console.firebase.google.com/u/0/project/child-growth-monitor/crashlytics/app/android:de.welthungerhilfe.cgm.scanner/issues/5aa0e3f78cb3c2fa63901e74)
- [x] will be removed [ScreenRecordActivity.java line 299](https://console.firebase.google.com/u/0/project/child-growth-monitor/crashlytics/app/android:de.welthungerhilfe.cgm.scanner/issues/5aa0e26a8cb3c2fa639007c4)

others:

- [ ] RecyclerDataAdapter.java – line 98
  - de.welthungerhilfe.cgm.scanner.adapters.RecyclerDataAdapter.getItemCount

- [ ] CreateDataActivity.java – line 410
  - de.welthungerhilfe.cgm.scanner.activities.CreateDataActivity.loadMeasures

- [x] GrowthDataFragment.java – line 138
  - de.welthungerhilfe.cgm.scanner.fragments.GrowthDataFragment.setChartData

- [ ] OverlaySurface.java – line 180
  - de.welthungerhilfe.cgm.scanner.tango.OverlaySurface.drawBabyOverlay

- [ ] OverlaySurface.java – line 131
  - de.welthungerhilfe.cgm.scanner.tango.OverlaySurface.surfaceCreated
